import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom'; // Import useNavigate
import '../LandingPage.css';

const schoolImage = '/school.jpg';
const logo = '/school.png';

const LandingPage = () => {
  const [modalContent, setModalContent] = useState(null);
  const navigate = useNavigate(); // Hook for navigation

const handleCTA = () => {
  navigate('/loading');
  setTimeout(() => {
    navigate('/checker');
  }, 3000);
};


  return (
    <div
      className="landing-page"
      style={{ backgroundImage: `url(${schoolImage})` }}
    >
      {/* Navbar */}
      <nav className="navbar">
        <div className="navbar-left">
          <img src={logo} alt="School Logo" className="logo" />
          <span className="title">LaUDMefy</span>
        </div>
        <div className="navbar-right">
          <button
            onClick={() =>
              setModalContent({
                title: 'About',
                body: `LaUDMefy is a web-based academic simulation tool designed for UDM students. 
                It helps estimate whether a student is on track to graduate with Latin honors such as 
                Cum Laude, Magna Cum Laude, or Summa Cum Laude. By inputting your academic records, 
                LaUDMefy can provide insights on where you stand and what you need to maintain or 
                improve to qualify for honors. This is especially helpful for long-term planning 
                and self-assessment during your academic journey.`
              })
            }
          >
            About
          </button>
          <button
            onClick={() =>
              setModalContent({
                title: 'Terms & Conditions',
                body: `LaUDMefy is intended for educational and informational purposes only. 
                The results generated by this tool are estimations based on the information 
                provided by the user. While we strive for accuracy, LaUDMefy does not guarantee 
                that the predictions are reflective of official academic evaluations. For official 
                graduation standing and honors qualification, students must consult their university's 
                registrar or academic office. By using LaUDMefy, you acknowledge and agree that the 
                creators are not liable for any academic decisions made based on the tool’s output.`
              })
            }
          >
            Terms & Conditions
          </button>
        </div>
      </nav>

      {/* Text Content */}
      <div className="landing-text">
        <h1>WILL I GRADUATE WITH LATIN HONORS?</h1>
        <p>
          LaUDMefy helps you simulate and track your academic performance to see
          if you're on the path to becoming Cum Laude, Magna Cum Laude, or Summa Cum Laude.
        </p>
        <button className="cta-button" onClick={handleCTA}>
          Check My Standing Now
        </button>
      </div>

      {/* Modal */}
      {modalContent && (
        <div className="modal-overlay">
          <div className="modal-box">
            <h2>{modalContent.title}</h2>
            <p>{modalContent.body}</p>
            <button className="close-btn" onClick={() => setModalContent(null)}>
              Close
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default LandingPage;
